FROM node:16-alpine

WORKDIR '/app'

COPY package.json . 

RUN npm install

# Is redundant if using Docker Volumes
# perhaps, can server as a production grade
# glow observation.
COPY . .

CMD [ "npm", "run", "start" ]